---
# tasks file for ssh
- name: Generate SSH key
  shell: ssh-keygen -t rsa -N "" -f /home/ubuntu/.ssh/id_rsa
  become_user: ubuntu

- name: Append SSH public key to authorized_keys
  shell: cat /home/ubuntu/.ssh/id_rsa.pub >> /home/ubuntu/.ssh/authorized_keys
  become_user: ubuntu

- name: Set permissions for authorized_keys
  shell: chmod 0640 /home/ubuntu/.ssh/authorized_keys
  become_user: ubuntu