---
# tasks file for hadoop
- name: Download hadoop
  shell: wget https://dlcdn.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz

- name: Extract archive
  shell: tar -xvzf hadoop-3.3.6.tar.gz

- name: Remove archive
  shell: rm hadoop-3.3.6.tar.gz

- name: Rename folder
  shell: mv hadoop-3.3.6 /usr/bin/hadoop

- name: Add lines to .bashrc
  blockinfile:
    path: ~/.bashrc
    block: |
      'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64'
      'export HADOOP_HOME=/usr/bin/hadoop'
      'export HADOOP_INSTALL=$HADOOP_HOME'
      'export HADOOP_MAPRED_HOME=$HADOOP_HOME'
      'export HADOOP_COMMON_HOME=$HADOOP_HOME'
      'export HADOOP_HDFS_HOME=$HADOOP_HOME'
      'export HADOOP_YARN_HOME=$HADOOP_HOME'
      'export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native'
      'export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin'
      'export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"'