---
# tasks file for hadoop
- name: Download hadoop
  shell: wget https://dlcdn.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz

- name: Extract archive
  shell: tar -xvzf hadoop-3.3.6.tar.gz

- name: Remove archive
  shell: rm hadoop-3.3.6.tar.gz

- name: Rename folder
  shell: mv hadoop-3.3.6 /usr/bin/hadoop

- name: Add JAVA HOME
  shell: export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

- name: Add HADOOP HOME
  shell: export HADOOP_HOME=/usr/bin/hadoop

- name: Add HADOOP INSTALL
  shell: export HADOOP_INSTALL=$HADOOP_HOME

- name: Add HADOOP MAPRED HOME
  shell: export HADOOP_MAPRED_HOME=$HADOOP_HOME

- name: Add HADOOP COMMON HOME
  shell: export HADOOP_COMMON_HOME=$HADOOP_HOME

- name: Add HADOOP HDFS HOME
  shell: export HADOOP_HDFS_HOME=$HADOOP_HOME

- name: Add HADOOP YARN HOME
  shell: export HADOOP_YARN_HOME=$HADOOP_HOME

- name: Add HADOOP COMMON LIB NATIVE DIR
  shell: export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
      
- name: Recreate PATH
  shell: export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin

- name: Add HADOOP OPTS
  shell: export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"

- name: Edit JAVA_HOME in hadoop-env.sh
  vars:
    hadoop_home: "{{ lookup('env', 'HADOOP_HOME') }}"
  shell: sed -i 's/^.*JAVA_HOME=\/.*/JAVA_HOME=\/usr\/lib\/jvm\/java-8-openjdk-amd64/' "{{ hadoop_home }}/etc/hadoop/hadoop-env.sh"

- name: Create Namenode directory
  become_user: ubuntu
  shell: mkdir -p ~/hadoopdata/hdfs/namenode

- name: Create Datanode directory
  become_user: ubuntu
  shell: mkdir -p ~/hadoopdata/hdfs/datanode

- name: Delete old config of core-site.xml
  vars:
    hadoop_home: "{{ lookup('env', 'HADOOP_HOME') }}"
  shell: head -n -2 "{{ hadoop_home }}/etc/hadoop/core-site.xml" > temp_core_site.xml && mv temp_core_site.xml "{{ hadoop_home }}/etc/hadoop/core-site.xml"

- name: Add new config to core-site.xml
  become_user: ubuntu
  vars:
    actual_hostname: "{{ ansible_hostname }}"
    hadoop_home: "{{ lookup('env', 'HADOOP_HOME') }}"
  blockinfile:
    path: "{{ hadoop_home }}/etc/hadoop/core-site.xml"
    marker: ""
    block: |
      <configuration>
        <property>
          <name>fs.defaultFS</name>
          <value>hdfs://{{ actual_hostname }}:9000</value>
        </property>
      </configuration>

- name: Delete old config of hdfs-site.xml
  vars:
    hadoop_home: "{{ lookup('env', 'HADOOP_HOME') }}"
  shell: head -n -3 "{{ hadoop_home }}/etc/hadoop/hdfs-site.xml" > temp_hdfs_site.xml && mv temp_hdfs_site.xml "{{ hadoop_home }}/etc/hadoop/hdfs-site.xml"

- name: Add new config to hdfs-site.xml
  become_user: ubuntu
  vars:
    hadoop_home: "{{ lookup('env', 'HADOOP_HOME') }}"
  blockinfile:
    path: "{{ hadoop_home }}/etc/hadoop/hdfs-site.xml"
    marker: ""
    block: |
      <configuration>
          <property>
          <name>dfs.replication</name>
          <value>1</value>
        </property>
        <property>
          <name>dfs.namenode.name.dir</name>
          <value>file:///home/ubuntu/hadoopdata/hdfs/namenode</value>
        </property>
        <property>
          <name>dfs.datanode.data.dir</name>
          <value>file:///home/ubuntu/hadoopdata/hdfs/datanode</value>
        </property>
      </configuration>

- name: Delete old config of mapred-site.xml
  vars:
    hadoop_home: "{{ lookup('env', 'HADOOP_HOME') }}"
  shell: head -n -3 "{{ hadoop_home }}/etc/hadoop/mapred-site.xml" > temp_mapred_site.xml && mv temp_mapred_site.xml "{{ hadoop_home }}/etc/hadoop/mapred-site.xml"

- name: Add new config to mapred-site.xml
  become_user: ubuntu
  vars:
    hadoop_home: "{{ lookup('env', 'HADOOP_HOME') }}"
  blockinfile:
    path: "{{ hadoop_home }}/etc/hadoop/mapred-site.xml"
    marker: ""
    block: |
      <configuration>
        <property>
          <name>yarn.app.mapreduce.am.env</name>
          <value>HADOOP_MAPRED_HOME=/usr/bin/hadoop/bin/hadoop</value>
        </property>
        <property>
          <name>mapreduce.map.env</name>
          <value>HADOOP_MAPRED_HOME=/usr/bin/hadoop/bin/hadoop</value>
        </property>
        <property>
          <name>mapreduce.reduce.env</name>
          <value>HADOOP_MAPRED_HOME=/usr/bin/hadoop/bin/hadoop</value>
        </property>
      </configuration>

- name: Delete old config of yarn-site.xml
  vars:
    hadoop_home: "{{ lookup('env', 'HADOOP_HOME') }}"
  shell: head -n -5 "{{ hadoop_home }}/etc/hadoop/yarn-site.xml" > temp_yarn_site.xml && mv temp_yarn_site.xml "{{ hadoop_home }}/etc/hadoop/yarn-site.xml"

- name: Add new config to yarn-site.xml
  become_user: ubuntu
  vars:
    hadoop_home: "{{ lookup('env', 'HADOOP_HOME') }}"
  blockinfile:
    path: "{{ hadoop_home }}/etc/hadoop/yarn-site.xml"
    marker: ""
    block: |
      <configuration>
        <property>
          <name>yarn.nodemanager.aux-services</name>
          <value>mapreduce_shuffle</value>
        </property>
      </configuration>


