---
# tasks file for apt
- name: install java
  apt:
    name: openjdk-8-jdk
    state: latest

- name: install ssh
  apt:
    name: ssh
    state: latest

- name: install net tools
  apt:
    name: net-tools
    state: latest