---
# tasks file for ssh
- name: Generate SSH key
  shell: echo -e " \n \n" | ssh-keygen -t rsa

- name: Append SSH public key to authorized_keys
  shell: cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

- name: Set permissions for authorized_keys
  ansible.builtin.file:
    path: ~/.ssh/authorized_keys
    mode: '0640'

